// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortenedReferenceDAL.DataBase;

namespace ShortenedReferenceDAL.Migrations
{
    [DbContext(typeof(ReferenceShortenerContext))]
    [Migration("20200824215823_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShortenedReferenceDAL.Models.ReferenceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountTransitions")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongReference")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortenedReference")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ReferenceInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
